# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='имя автора')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название заявления')),
            ],
            options={
                'verbose_name': 'заявление',
                'verbose_name_plural': 'заявления',
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Statement', verbose_name='заявление'),
        ),
    ]
